type UnionStringArray<T extends Readonly<string[]>> = T[number]

/**
 * @internal
 */
export const threeElements = [
    "ambientLightProbe",
    "arrayCamera",
    "arrowHelper",
    "audioListener",
    "axesHelper",
    "bone",
    "box3Helper",
    "boxHelper",
    "camera",
    "cameraHelper",
    "cubeCamera",
    "directionalLight",
    "directionalLightHelper",
    "gridHelper",
    "group",
    "hemisphereLight",
    "hemisphereLightHelper",
    "hemisphereLightProbe",
    "immediateRenderObject",
    "instancedMesh",
    "lOD",
    "light",
    "lightProbe",
    "lineLoop",
    "lineSegments",
    "mesh",
    "orthographicCamera",
    "perspectiveCamera",
    "planeHelper",
    "pointLight",
    "pointLightHelper",
    "points",
    "polarGridHelper",
    "positionalAudio",
    "rectAreaLight",
    "scene",
    "skeleton",
    "skeletonHelper",
    "skinnedMesh",
    "spotLight",
    "spotLightHelper",
    "sprite",
] as const
export type ThreeElements = UnionStringArray<typeof threeElements>
